[package]
name = "usrnet"
version = "0.1.0"
authors = ["Andrei Maximov <andrei.maximov@gmail.com>"]

[dependencies]
byteorder = "1.0"
libc = "0.2"
mock_derive = "0.7.0"

[dev-dependencies]
assert_matches = "1.1.0"
clap = "2.29"

[[example]]
name = "arping"

[[example]]
name = "ping"

[[example]]
name = "tap_up"
