# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_check_update = false

  config.vm.synced_folder "../", "/usrnet"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "file", source: ".tmux.conf", destination: ".tmux.conf"
  config.vm.provision "file", source: ".zshrc", destination: ".zshrc"
  config.vm.provision "shell", path: "provision.sh", privileged: false

  config.vm.define "dev-1", primary: true do |dev|
    dev.vm.network "private_network", ip: "10.0.0.101"
    dev.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

  config.vm.define "dev-2" do |dev|
    dev.vm.network "private_network", ip: "10.0.0.102"
    dev.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
